-- Four additional original articles for the Sona blog.
-- Appended as a separate migration so the earlier seed migration stays untouched.

insert into public.blog_posts (slug, title, description, tag, read_mins, body, published)
values
(
  'why-your-video-calls-drop-and-what-actually-helps',
  'Why Video Calls Drop (and What Actually Helps)',
  'Blaming "bad WiFi" is usually wrong. Here''s what actually causes calls to freeze or disconnect, and the handful of things that genuinely fix it.',
  'Guides', 6,
  E'When a video call freezes or drops, the instinctive explanation is always the same: bad WiFi. Sometimes that''s true. More often, the real cause is something more specific, and knowing the difference is the fastest way to actually fix it instead of just restarting your router and hoping.\n\nThe first thing worth understanding is that video calls are far more sensitive to inconsistency than to raw speed. A connection that''s slow but steady will hold a call together better than a fast connection that dips every few seconds — which is exactly what happens on WiFi shared with someone streaming, downloading, or backing up photos in the background. If your calls stutter at predictable moments, check what else is on the network before assuming your internet plan is too slow.\n\nDistance from the router matters more than most people account for. Video calls typically need a stronger, more stable signal than browsing or messaging, so a connection that feels "fine" for everything else can still struggle here. If you regularly call from a bedroom or another room away from the router, that alone is often the entire explanation — moving closer, or switching from WiFi to your phone''s mobile data for the call, frequently fixes it outright.\n\nDevice load plays a bigger role than people expect too. Video calls are genuinely demanding on your device''s processor, especially with camera effects, background blur, or screen sharing active at the same time. On an older or lower-powered device, running several other apps in the background while on a call can cause exactly the kind of stutter that looks like a network problem but isn''t. Closing unused apps before an important call is a small habit that measurably helps.\n\nWhen a call does drop, Sona tries to reconnect automatically for a short window rather than ending the call outright — you''ll see a brief "Reconnecting…" state instead of being kicked out immediately. If it doesn''t recover within that window, rejoining from the call notification is faster than starting a whole new call, since it reuses the existing session rather than renegotiating from scratch.\n\nFor calls where reliability really matters — an interview, a client meeting — the most effective single thing you can do isn''t a setting inside Sona at all: switch off WiFi and use mobile data instead, or the reverse, whichever is more consistently strong at your specific location. Testing which one holds up before the call, rather than during it, is the difference between a smooth call and a frustrating one.',
  true
),
(
  'the-case-for-turning-off-most-of-your-notifications',
  'The Case for Turning Off Most of Your Notifications',
  'Not every message deserves an interruption. A practical look at which notifications are actually worth keeping on, and which ones are just training you to check your phone.',
  'Guides', 5,
  E'Every notification you get trains a small habit: check phone, glance, unlock, scroll. Multiply that by every group you''re in, and it adds up to something most people never actually chose — they just never turned anything off. It''s worth being deliberate about which conversations genuinely need to interrupt you in real time, and which ones you''re fine catching up on later.\n\nA useful test: would you be upset if you found out about this message an hour late? For a close friend messaging you directly, probably yes — keep that notification on. For a 40-person group chat about weekend plans, almost certainly not — you''ll see it next time you open the app regardless, and nothing is lost by not being interrupted the moment it arrives.\n\nGroup chats are the biggest source of notification fatigue by far, simply because of volume — one active group can generate more notifications in an hour than all your one-on-one chats combined in a day. Muting a group doesn''t mean leaving it or missing anything; you still receive every message, you just aren''t interrupted for each one. Sona lets you mute for 8 hours, a week, or indefinitely, which covers both "I''m in a meeting" and "I''m fine catching this group in my own time from now on."\n\nThere''s a middle option worth knowing about too: muting a group but keeping notifications on for @mentions within it. This is the right setting for a group you care about but that''s too high-volume to track message by message — you stay silent for the general chatter but still get pinged the moment someone specifically needs your attention.\n\nOne-on-one chats are usually worth leaving alone, precisely because the volume is naturally lower and each message is more likely to actually be for you specifically. The goal isn''t to silence everything — it''s to stop treating a 40-person group thread with the same urgency as a message from your closest friend, when they clearly aren''t the same thing.\n\nIf you''ve never touched your notification settings since installing the app, it''s worth ten minutes to walk through your most active chats and mute the ones that are really just background noise. The messages don''t disappear — you just stop being interrupted by them.',
  true
),
(
  'sharing-large-files-without-losing-quality',
  'Sharing Large Files Without Losing Quality',
  'Why a photo or video sometimes looks worse after you send it, and what to actually do about it — including when to just send a file instead of a picture.',
  'Guides', 5,
  E'You take a sharp photo, send it in a chat, and the version the other person receives looks noticeably softer or more compressed than what''s on your camera roll. This isn''t a bug — it''s a deliberate tradeoff almost every messaging app makes, and understanding it helps you know when to work around it.\n\nMessaging apps compress photos and videos sent as regular media because most people, most of the time, want speed over resolution — a large uncompressed photo can take far longer to send and receive on a weak connection, especially for the person on the other end. Sona compresses media sent normally for exactly that reason: fast, reliable delivery for the vast majority of everyday photos and clips where a little quality loss doesn''t actually matter.\n\nWhen it does matter — a design file, a screenshot with small text that needs to stay legible, a photo you want printed — send it as a document instead of a photo. Documents aren''t compressed the way images are, so what you send is what arrives, byte for byte. The tradeoff is a slightly less convenient viewing experience (it opens as a file rather than inline in the chat), which is a reasonable price for guaranteed quality.\n\nVideo works similarly but with a bigger quality gap, since video compression is far more aggressive than photo compression by necessity — an uncompressed video file is enormous. If you''re sharing a video where quality genuinely matters, consider whether the recipient actually needs the full-resolution original, or whether a cloud storage link (Drive, Dropbox, whatever you already use) is a better fit than sending it as chat media at all.\n\nSona Pro raises the file size ceiling substantially, which mainly helps with documents and video rather than photos — since photos are compressed either way, a higher size limit doesn''t change how a normal photo looks, it mainly matters for sending original, uncompressed files as documents without hitting a size wall.\n\nThe practical rule: default photo/video sending is fine for anything casual, but the moment quality actually matters — text needs to stay sharp, colors need to stay accurate, resolution needs to survive — send it as a file, not a picture.',
  true
),
(
  'install-sona-like-a-real-app-no-app-store-needed',
  'Install Sona Like a Real App — No App Store Needed',
  'Sona works as a Progressive Web App, which means you can install it to your home screen, use it offline, and get real push notifications, all without downloading anything from an app store.',
  'Product', 4,
  E'"Progressive Web App" sounds like a technical detail, but what it actually means for you is simple: Sona can be installed on your phone or computer like a real app — home screen icon, its own window, push notifications, offline access to recent chats — without you ever visiting an app store or downloading a separate installer.\n\nOn most Android phones, open Sona in your browser, tap the menu, and choose "Add to Home Screen" or "Install App" — the exact wording depends on your browser, but the option is there. On iPhone, open Sona in Safari specifically (this doesn''t work in Chrome or other browsers on iOS due to Apple''s restrictions), tap the Share icon, and choose "Add to Home Screen." Either way, you end up with an icon that opens Sona in its own full-screen window, indistinguishable from an app you''d have downloaded from a store.\n\nOn desktop, Chrome and Edge both show an install icon in the address bar when you visit Sona — clicking it installs a standalone desktop app version, separate from your browser tabs, that you can pin to your taskbar or dock.\n\nThe practical benefits go beyond convenience. Installed this way, Sona can show real push notifications the same way a native app does, even when your browser itself is closed. Recently viewed chats are cached, so you can open the app and read your last few conversations even with no connection at all, though obviously new messages need an internet connection to arrive.\n\nThere''s no download size to worry about and no separate update process — because it''s fundamentally a website wrapped in an app-like shell, it''s always running the current version the moment you open it, with no "update available" prompts or manual downloads. This is also why there''s no separate app store listing to search for: the install happens directly from your browser, from the actual sona.chat address, which is worth double-checking if you''re installing on someone else''s recommendation, to make sure you''re getting the real thing.',
  true
)
on conflict (slug) do nothing;
